fix(test): Fix flaky test about ShuffleServerMetricsTest#testStorageCounter (#2142)
### What changes were proposed in this pull request?

Clear metrics in case of other test update the metrics value.

### Why are the changes needed?

Fix the flaky test.

```
Error:  Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.046 s <<< FAILURE! - in org.apache.uniffle.server.ShuffleServerMetricsTest
Error:  testStorageCounter  Time elapsed: 0.008 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1.0> but was: <3.0>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:86)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:81)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1010)
	at org.apache.uniffle.server.ShuffleServerMetricsTest.testStorageCounter(ShuffleServerMetricsTest.java:176)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

UT

(cherry picked from commit 422aa36955b177bc4c8d9ef8f9062b11bbdc5002)