[#2030] fix(client-spark): Remove javax and logging from relocation list to solve NoClassDefFoundError (#2029)
### What changes were proposed in this pull request?

Do not relocate javax to avoid NoClassDefFoundError issue.

### Why are the changes needed?

Fix: #2030

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Thanks for the verify check by @zhengchenyu . This is not reproduced on my env.

(cherry picked from commit 95537cd21cb02f3bddd256bbe311a05d68726f29)